// <auto-generated />
using System;
using EntityFrameworkCore.Extensions.Samples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace EntityFrameworkCore.Extensions.Samples.Migrations
{
    [DbContext(typeof(Program.SampleContext))]
    [Migration("20260820170557_AddSpatialIndexes")]
    partial class AddSpatialIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountCardNumber")
                        .HasColumnType("int")
                        .HasAnnotation("DynamicDataMasking", "random(10, 100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DynamicDataMasking", "partial(2, \"XX-XX\", 1)");

                    b.Property<string>("SampleProperty1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleProperty2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DynamicDataMasking", "default()");

                    b.Property<string>("Surname2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.HasKey("Id");

                    b.HasIndex("Location")
                        .HasDatabaseName("SIX_Places_Location")
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndex", true);

                    b.ToTable("Places");
                });

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("SIX_Regions_Boundary")
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndex", true)
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndexBoundingBoxXMax", 180.0)
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndexBoundingBoxXMin", -180.0)
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndexBoundingBoxYMax", 90.0)
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndexBoundingBoxYMin", -90.0)
                        .HasAnnotation("EntityFrameworkCore.Extensions:SpatialIndexCellsPerObject", 32);

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Order", b =>
                {
                    b.HasOne("EntityFrameworkCore.Extensions.Samples.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityFrameworkCore.Extensions.Samples.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
